version: '3.8'
services:
  frontend:
    image: pramodkhatik/scm-frontend-image
    container_name: scm-frontend-cntr
    ports:
      - 5173:5173
    networks:
      - scmnw
  backend:
    image: pramodkhatik/scm-backend-image
    container_name: scm-backend-cntr
    ports:
      - 8081:8081
    networks:
      - scmnw
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=smartcontactmanager
      - DB_USER=root
      - DB_PASSWORD=root
  db:
    image: mysql:8.0.29
    container_name: mysql-container
    ports:
      - 3306:3306
    networks:
      - scmnw
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=smartcontactmanager
    volumes:
      - mysqldb:/var/lib/mysql
networks:
  scmnw:
volumes:
  mysqldb: