server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql-container:3306/smartcontactmanager?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    '[org.springframework.security]': DEBUG
    
project:
  image: images/

contact:
  image: images/contact/
